### ISSUE TITLE
andere beschreibung

### ISSUE THREAD

**Issue by Ayumix3** [Greif5/Vokabeltrainer#20]
https://github.com/Greif5/Vokabeltrainer/blob/53685642aae78e03e98bb8094d077e843f9798ff/src/List.java#L141

**Comment by Greif5** [comment]
Hab den Kommentar ein klein wenig umgeschrieben, er sollte jetzt verständlicher sein.
https://github.com/Greif5/Vokabeltrainer/commit/bced690e8dca19452d591fb316c4ba434d0f45cf
