### ISSUE TITLE
Erkennungswort bennen 

### ISSUE THREAD

**Issue by Ayumix3** [Greif5/Vokabeltrainer#21]
https://github.com/Greif5/Vokabeltrainer/blob/53685642aae78e03e98bb8094d077e843f9798ff/src/List.java#L232

**Comment by Greif5** [comment]
Hab das Wort hinzugefügt.
https://github.com/Greif5/Vokabeltrainer/commit/bec6e76e7c2ed4cfe2dac80b4c36b54945ac5f46
