### ISSUE TITLE
hilfpointer bennen

### ISSUE THREAD

**Issue by Ayumix3** [Greif5/Vokabeltrainer#22]
https://github.com/Greif5/Vokabeltrainer/blob/53685642aae78e03e98bb8094d077e843f9798ff/src/List.java#L400

**Comment by Greif5** [comment]
Hab den Kommentar verbessert.
https://github.com/Greif5/Vokabeltrainer/commit/f82c4fa123f2ff02f3211b36655de3ff5990a41c

Es gab das gleiche Problem auch in der UserListe.
