### ISSUE TITLE
erwähnen des benutzens einer regular expression in der funktion

### ISSUE THREAD

**Issue by Ayumix3** [Greif5/Vokabeltrainer#23]
https://github.com/Greif5/Vokabeltrainer/blob/53685642aae78e03e98bb8094d077e843f9798ff/src/List.java#L382

**Comment by Greif5** [comment]
Habs gefixt.
https://github.com/Greif5/Vokabeltrainer/commit/e62fbc3b2c279a04dc74b424ac2a157fec58a580

Es gab das gleiche Problem auch in der UserList.
